language: java
sudo: false
before_deploy:
  - echo "Build Directory Target: $TRAVIS_BUILD_DIR/*"
deploy:
  provider: releases
  user: $GIT_HUB1
  password: $GIT_HUB2
  file: "$TRAVIS_BUILD_DIR/*"
  skip_cleanup: true
  on:
    tags: false
script:
 - mvn clean install
