language: java
sudo: false
before_install:

after_install:
 - mvn -Dmessage="CI Build Update" scm:checkin

deploy:
  provider: releases
  api_key: $GIT_HUB3
  file_glob: true
  file: "/home/travis/.m2/repository/ext/project/ms/msproject/0.0.1-SNAPSHOT/msproject-0.0.1-SNAPSHOT.jar"
  skip_cleanup: true
  on:
    tags: true
