language: java
sudo: false
before_install:
  - echo " " >> pom.xml
  - git checkout origin/master
after_script:
 - mvn -Dincludes="pom.xml" scm:add
 - mvn -Dmessage="CI Build Update" -DpushChanges=true scm:checkin

deploy:
  provider: releases
  api_key: $GIT_HUB3
  file_glob: true
  file: "/home/travis/.m2/repository/ext/project/ms/msproject/0.0.1-SNAPSHOT/msproject-0.0.1-SNAPSHOT.jar"
  script: 
    - chmod -R 755 ./.travis/after_success.sh
    - ./.travis/after_success.sh
  skip_cleanup: true
  on:
    tags: true
